language: go

go:
  - 1.14.x

script:
  - git clone https://github.com/bostontrader/okprobe
  - cd okprobe
  - go build

  # Test using an OKCatbox, not a real OKEx server
  - CATBOX_URL=http://185.183.96.73:8090
  - CATBOX_CREDENTIALS=okcatbox-read.json
  - curl -X POST $CATBOX_URL/catbox/credentials --output CATBOX_CREDENTIALS

  # funding
  - ./okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt currencies
  - ./okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt deposit-address
  - ./okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt deposit-history
  - ./okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt wallet
  - ./okprobe -url $CATBOX_URL -errors -keyfile $CATBOX_CREDENTIALS -endpnt withdrawal-fee

  # spot
  - ./okprobe -url $CATBOX_URL -keyfile $CATBOX_CREDENTIALS -errors -endpnt accounts

