language: go

go:
  - 1.14.x

install:
  - go get github.com/bostontrader/okcatbox
  - go run github.com/bostontrader/okcatbox

script:
  - go build
  - ./okprobe -url http://localhost:8090 -endpnt withdrawal-fee -keyfile  okcatbox-read.json