language: go

go:
  - 1.14.x

script:
  - go get github.com/bostontrader/okcatbox
  - go get github.com/bostontrader/okconnect
  - go get github.com/bostontrader/okprobe
  - go get github.com/bostontrader/oktest

  - oktest
