language: go

go:
  - 1.14.x

install:
  - go get github.com/bostontrader/okcatbox
  - go run github.com/bostontrader/okcatbox &

script:
  - git clone https://github.com/bostontrader/okprobe
  - cd okprobe
  - go build
  - ./okprobe -url http://localhost:8090 -keyfile okcatbox-read.json -errors -endpnt currencies
  - ./okprobe -url http://localhost:8090 -keyfile okcatbox-read.json -errors -endpnt deposit-address
  - ./okprobe -url http://localhost:8090 -keyfile okcatbox-read.json -errors -endpnt deposit-history
  - ./okprobe -url http://localhost:8090 -keyfile okcatbox-read.json -errors -endpnt wallet
  - ./okprobe -url http://localhost:8090 -keyfile okcatbox-read.json -errors -endpnt withdrawal-fee
